language: r

r:
- oldrel
- release
- devel

warnings_are_errors: true

sudo: required

addons:
  apt:
    sources:
      - debian-sid

apt_packages:
- libudunits2-dev
- libnetcdf-dev
- libproj-dev
- libfreetype6-dev

r_binary_packages:
- proj4

r_github_packages:
  - jimhester/covr

env:
  global:
  - _R_BUILD_COMPACT_VIGNETTES_="gs+qpdf"
  - _R_CHECK_COMPACT_VIGNETTES_="gs+qpdf"

after_success:
  - Rscript -e 'library(covr);codecov()'
