language: r

warnings_are_errors: true

sudo: required

apt_packages:
- libudunits2-dev
- libnetcdf-dev

r_binary_packages:
- proj4

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
