language: r

warnings_are_errors: true

sudo: required

apt_packages:
- libudunits2-dev
- libnetcdf-dev

r_binary_packages:
- proj4

r_github_packages:
  - jimhester/covr

env:
  global:
  - _R_BUILD_COMPACT_VIGNETTES_="gs+qpdf"
  - _R_CHECK_COMPACT_VIGNETTES_="gs+qpdf"

after_success:
  - Rscript -e 'library(covr);codecov()'
