---
title: "model-calibration-species"
author: "Alexander Keth"
date: '`r Sys.Date()`'
output: 
  pdf_document:
    toc: true
    number_sections: true
    fig_width: 10
    fig_height: 15
    fig_caption: true
geometry: margin = 0.5cm
vignette: >
  %\VignetteIndexEntry{model-calibration-species}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, echo = FALSE}
library("atlantistools")
library("gridExtra")

# NOTE: This vigentte is optimised for longer simulation runs. Therefore the output is not as pleasant
# due to the fact that the dummy setas file have a running time of 3 years.

# This section is used to read in the data created with preprocess(). 
# You can do this however you like. Either make sure the data is already
# present in your workspace as object "result" or load the data from *.rda with load().
# Unfortunately it is nearly impossible to demonstarte this with the package itself because the data is 
# already loaded as soon as you load the package with "library()". Therefore I have to 
# assign the data by hand otherwise the vignette will fail.
# Please comment the next line in your personal version of this *.Rmd file and add your
# personal loading technique.
result <- preprocess_setas

# Pass the species you want to plot.
species <- c("Shallow piscivorous fish", "Small planktivorous fish")

# You should be able to build the vignette either by clicking on "Knit-PDF" or with
# rmarkdown::render("model-calibration.Rmd")
```

\newpage

# Overview species 

```{r, echo = FALSE}
plots <- lapply(species, plot_species, data_pre = result)
marrangeGrob(grobs = plots, nrow = 1, ncol = 1)
```

library(ggplot2)
pl <- lapply(1:11, function(.x) qplot(1:10, rnorm(10), main=paste("plot", .x)))
ml <- marrangeGrob(pl, nrow=2, ncol=2)
