---
title: "model-feeding"
author: "Alexander Keth"
date: '`r Sys.Date()`'
output: pdf_document
toc: true
number_sections: true
classoption: landscape
geometry: margin = 0.5cm
---

```{r, echo = FALSE}
library("atlantistools")
library("ggplot2")

# This section is used to read in the data! You can do this however you like.
# I will give you an examples how this can be done. But you can chose any other way!
# PLease keep in mind that the final list should be named "result".

# Solution:
# Set your model paths here
# model_paths <- c(file.path("Z:", "Atlantis_models", "Runs", "dummy_01_ATLANTIS_NS"),
#                  file.path("Z:", "Atlantis_models", "Runs", "dummy_02_ATLANTIS_NS"),
#                  file.path("Z:", "Atlantis_models", "Runs", "dummy_03_ATLANTIS_NS"))
#
# Read in the preprocessed dataframes from each simulation!
# store_data <- list()
# for (i in seq_along(model_paths)) {
#   load(file.path(model_paths[i], "preprocess-north-sea.rda"))
#   store_data[[i]] <- result
# }

# Unfortunately it is nearly impossible to demonstarte this with the package itself because the data is 
# already loaded as soon as you load the package with "library()". Therefore I have to create some dummy
# data to demonstrate the rest of the vignette. Simply comment this out in your final *.Rmd file.
dummy_setas <- function(list, mult) {
  for (i in seq_along(list)) {
    mult <- rep_len(mult, length.out = nrow(list[[i]]))
    list[[i]][, ncol(list[[i]])] <- list[[i]][, ncol(list[[i]])] * mult
  }
  return(list)
}

store_data <- list(preprocess_setas, 
                   dummy_setas(preprocess_setas, mult = c(1, 1.2)),
                   dummy_setas(preprocess_setas, mult = c(2, 2.2)))

# Now we have to combine the data from the different simulations with "combine_runs()".
# Please edit the strings passed to "runs" at this point!
result <- combine_runs(outs = store_data, runs = c("run1", "run2", "run3"))

# And adjust the ploting sizes (here and throughout this document) to your likings.
dw1 <- 25
dh1 <- 15
dh2 <- 11

# You should be able to build the vignette either by clicking on "Knit-PDF" or with
# rmarkdown::render("model-comparison.Rmd")
```

\newpage

## Diet plots
```{r, fig.width = 14, fig.height = 8}
sum_bio <- agg_sum(result$biomass, groups = c("time", "run"))
ggplot2::ggplot(sum_bio, ggplot2::aes(x = time, y = atoutput, colour = run)) +
  ggplot2::geom_line() +
  ggplot2::coord_cartesian(expand = FALSE) +
  ggplot2::guides(colour = ggplot2::guide_legend(ncol = 1)) +
  theme_atlantis()
```

\newpage

## Biomass timeseries
```{r, fig.width = dw1, fig.height = dh1}
plot_ts(result$biomass) %>% plot_add_run(.) %>% update_labels(labels = list(y = "Biomass [t]"))
```

\newpage

## Relative biomass timeseries
```{r, fig.width = dw1, fig.height = dh1}
plot_calibrate(result$biomass) %>% plot_add_run(.)
```

\newpage

## Physics
```{r, fig.width = 30, fig.height = 12}
plot_physics(result$physics) %>% plot_add_run(.) %>% ggplot2::guides(colour = ggplot2::guide_legend(ncol = 1))
```













