---
title: "model-comparison"
author: "Alexander Keth"
date: '`r Sys.Date()`'
output: 
  pdf_document:
    toc: true
    number_sections: true
    fig_width: 25
    fig_height: 6
    fig_caption: true
classoption: landscape
geometry: margin = 0.5cm
vignette: >
  %\VignetteIndexEntry{model-comparison}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, echo = FALSE}
library("atlantistools")
library("ggplot2")

# NOTE: This vigentte is optimised for longer simulation runs. Therefore the output is not as pleasant
# due to the fact that the dummy setas file have a running time of 3 years.

# This section is used to read in the data created with preprocess() for each simulation. 
# You can do this however you like. You can use the following code snippet to read in
# the preprocessed file (*.rda) from different locations. dirs should be a vector of character
# strings giving the directories of your simulations. Please change "preprocess.rda" to the
# filename you choose for the output generated with preprocess(). 
# Please note that the final data should be a list of your simulations.
# Each list entry should itself be a list of datarframes created with preprocess(). 

# dirs <- file.path(dirs, "preprocess.rda")
# store_data <- vector("list", length = length(dirs))
# for (i in seq_along(dirs)) {
#   load(file.path(dirs[i])
#   store_data[[j]] <- result
# }

# Unfortunately it is nearly impossible to demonstarte this with the package itself because the data is 
# already loaded as soon as you load the package with "library()". In addition there is only one
# simulation available therefore I have to create some dummy data to demonstrate the rest of 
# the vignette. # Please comment out the next section in your personal version of this *.Rmd file.
 
dummy_setas <- function(list, mult) {
  for (i in seq_along(list)) {
    mult <- rep_len(mult, length.out = nrow(list[[i]]))
    list[[i]][, ncol(list[[i]])] <- list[[i]][, ncol(list[[i]])] * mult
  }
  return(list)
}
store_data <- list(preprocess_setas, 
                   dummy_setas(preprocess_setas, mult = c(1, 1.2)),
                   dummy_setas(preprocess_setas, mult = c(2, 2.2)))

# Now we have to combine the data from the different simulations with "combine_runs()".
# Please edit the strings passed to "runs" at this point.
result <- combine_runs(outs = store_data, runs = c("run1", "run2", "run3"))

# And adjust the ploting sizes (at the top and throughout this document) to your likings.

# You should be able to build the vignette either by clicking on "Knit-PDF" or with
# rmarkdown::render("model-comparison.Rmd")
```

\newpage

# Whole system biomass
```{r, fig.width = 14, fig.height = 8}
sum_bio <- agg_data(result$biomass, groups = c("time", "run"), fun = sum)
ggplot2::ggplot(sum_bio, ggplot2::aes(x = time, y = atoutput, colour = run)) +
  ggplot2::geom_line() +
  ggplot2::coord_cartesian(expand = FALSE) +
  ggplot2::guides(colour = ggplot2::guide_legend(ncol = 1)) +
  theme_atlantis()
```

\newpage

# Biomass timeseries
```{r}
plot_ts(result$biomass) %>% plot_add_run(.) %>% update_labels(labels = list(y = "Biomass [t]"))
```

\newpage

# Relative biomass timeseries
```{r}
plot_calibrate(result$biomass) %>% plot_add_run(.)
```

\newpage

# Physics
```{r, fig.width = 30, fig.height = 12}
plot_physics(result$physics) %>% plot_add_run(.)
```













